name: 'vmn-versioning'
description: 'Production grade solution for automatic versioning with full support for semantic versioning (Semver). Agnostic to programming language.'
branding:
  icon: trending-up
  color: green
inputs:
  release-mode:
    type: choice
    description: Desired Release Mode
    options:
      - major
      - minor
      - patch
    required: true
    default: patch
  app-name:
    description: "Name of the app to stamp"
    required: true
outputs:
  verstr:
    description: 'The version after stamping'
runs:
  using: 'node18'
  main: 'index.js'
