name: 'vmn-versioning'
description: 'Production grade solution for git-based automatic versioning and 
              state recovery solution agnostic to language or architecture 
              full support for semantic versioning (Semver)'
branding:
  icon: trending-up
  color: green
inputs:
  release-mode:
    type: choice
    description: Desired Release Mode
    options:
      - major
      - minor
      - patch
    required: true
    default: patch
  app-name:
    description: "Name of the app to stamp"
    required: true
outputs:
  verstr:
    description: 'The version after stamping'
runs:
  using: 'node16'
  main: 'dist/index.js'
