name: 'Automated versioning'
description: 'vmn based, production grade solution for versioning agnostic to language. Full support for semantic versioning (Semver).'
branding:
  icon: trending-up
  color: green
inputs:
  release-mode:
    type: choice
    description: Desired Release Mode
    options:
      - major
      - minor
      - patch
    required: true
    default: patch
  app-name:
    description: "Name of the app to stamp"
    required: true
outputs:
  verstr:
    description: 'The version after stamping'
runs:
  using: 'node16'
  main: 'dist/index.js'
