name: 'vmn-stamping'
description: 'Everything you need for stamping'
inputs:
  release-mode:
    type: choice
    description: Desired Release Mode
    options:
      - major
      - minor
      - patch
    required: true
  app-name:
    description: "name"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install vmn
      shell: bash
      run: pip3 install vmn
    - name: Prepare vmn env
      shell: bash
      run: vmn init || vmn init-app ${{inputs.app-name}} || exit 0
    - name: Advance version
      shell: bash
      run: "vmn stamp -r ${{inputs.release-mode}} ${{inputs.app-name}}"
